version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Installing Node.js 24..."
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install --production
  build:
    commands:
      - echo "Build completed on `date`"
  post_build:
    commands:
      - echo "Preparing artifact for Elastic Beanstalk..."

artifacts:
  files:
    - '**/*'
  discard-paths: no
